// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sRlAavH4Z7DguT2F20lIigzgom93k0Q',
    appId: '1:772819182901:web:96f9a77b7f64435941187c',
    messagingSenderId: '772819182901',
    projectId: 'rentend',
    authDomain: 'rentend.firebaseapp.com',
    storageBucket: 'rentend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PT_pz7AHBLJ_ZRUCD6apsZ8f4MzCTpA',
    appId: '1:772819182901:android:f68e5f77360ce83341187c',
    messagingSenderId: '772819182901',
    projectId: 'rentend',
    storageBucket: 'rentend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIGuQmqfY6YIlQaa4A5PETPJFQQtUZwg',
    appId: '1:772819182901:ios:ae0df363f596f11b41187c',
    messagingSenderId: '772819182901',
    projectId: 'rentend',
    storageBucket: 'rentend.appspot.com',
    iosBundleId: 'com.example.rentend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeIGuQmqfY6YIlQaa4A5PETPJFQQtUZwg',
    appId: '1:772819182901:ios:ae0df363f596f11b41187c',
    messagingSenderId: '772819182901',
    projectId: 'rentend',
    storageBucket: 'rentend.appspot.com',
    iosBundleId: 'com.example.rentend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6sRlAavH4Z7DguT2F20lIigzgom93k0Q',
    appId: '1:772819182901:web:ec71c2d8b69d8b7c41187c',
    messagingSenderId: '772819182901',
    projectId: 'rentend',
    authDomain: 'rentend.firebaseapp.com',
    storageBucket: 'rentend.appspot.com',
  );
}
